export const projects = [
  {
    slug: "todo",
    num: "01",
    title: "Todo",
    cat: "Web Application",
    url: "#",
    img: "/screenshots/todo.jpg",
    bg: "#F0EBE3",
    description: "A modern and intuitive task management web application. Clean interface with a focus on usability and productivity.",
    services: ["Web Design", "Web Development"],
    year: "2024",
  },
  {
    slug: "sergi",
    num: "02",
    title: "Sergi",
    cat: "E-Commerce Website",
    url: "#",
    img: "/screenshots/sergi.jpg",
    bg: "#EDE6DC",
    description: "A premium e-commerce experience built with modern technologies. Fast, elegant and conversion-focused.",
    services: ["Web Design", "Web Development", "E-Commerce"],
    year: "2024",
  },
  {
    slug: "villa-gjecaj",
    num: "03",
    title: "Villa Gjecaj",
    cat: "Hotel Website",
    url: "https://villagjecaj.com",
    img: "/screenshots/villagjecaj.jpg",
    bg: "#E8E2D8",
    description: "A full hotel and restaurant website for Villa Gjecaj, one of Albania's most scenic eco-friendly destinations. Booking integration, multilingual, and SEO optimised.",
    services: ["Web Design", "Web Development", "SEO", "Booking Integration"],
    year: "2024",
  },
  {
    slug: "baby-gifts-albania",
    num: "04",
    title: "Baby Gifts Albania",
    cat: "E-Commerce Website",
    url: "#",
    img: "/screenshots/babygifts.jpg",
    bg: "#F0EBE3",
    description: "A charming e-commerce platform for baby gifts and accessories. Intuitive shopping experience with a warm, friendly design.",
    services: ["Web Design", "Web Development", "E-Commerce"],
    year: "2024",
  },
  {
    slug: "dentist",
    num: "05",
    title: "Dentist",
    cat: "Healthcare Website",
    url: "#",
    img: "/screenshots/dentist.jpg",
    bg: "#E4DDD2",
    description: "A clean and professional website for a dental clinic. Appointment booking, service presentation and SEO optimised for local search.",
    services: ["Web Design", "Web Development", "SEO"],
    year: "2024",
  },
  {
    slug: "archi-forma",
    num: "06",
    title: "Archi-Forma",
    cat: "Architecture Website",
    url: "#",
    img: "/screenshots/archforma.jpg",
    bg: "#E8E2D8",
    description: "A sophisticated portfolio website for an architecture studio. Minimal, elegant and focused on showcasing projects with impact.",
    services: ["Web Design", "Web Development"],
    year: "2024",
  },
  {
    slug: "mb-cartongesso",
    num: "07",
    title: "M.B Cartongesso",
    cat: "Construction Website",
    url: "#",
    img: "/screenshots/mb.jpg",
    bg: "#EDE6DC",
    description: "A professional website for a construction and interior finishing company. Clean layout with service presentation and contact integration.",
    services: ["Web Design", "Web Development"],
    year: "2024",
  },
];
